# =====================================================
# FASTPRINT — Configuration Spring Boot
# =====================================================

# --- Serveur ---
server.port=8080

# --- Base de données MySQL (XAMPP) ---
spring.datasource.url=jdbc:mysql://localhost:3306/fastprint?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
# validate : Hibernate vérifie que tes entités Java correspondent
# aux tables existantes, sans les modifier ni les recréer.
# C'est le bon mode ici car tu as déjà créé les tables manuellement.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Désactiver temporairement Spring Security ---
# On désactive le formulaire de login automatique de Spring Security
# le temps de mettre en place notre propre système d'auth (JWT).
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration